// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Map          = require("bs-platform/lib/js/map.js");
var Curry          = require("bs-platform/lib/js/curry.js");
var $$String       = require("bs-platform/lib/js/string.js");
var Caml_oo_curry  = require("bs-platform/lib/js/caml_oo_curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var ContextMap = $$Map.Make([$$String.compare]);

var class_tables = [
  0,
  0,
  0
];

function create(metaData) {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table([
          "add",
          "get"
        ]);
    var ids = CamlinternalOO.new_methods_variables($$class, [
          "get",
          "add"
        ], ["data"]);
    var get = ids[0];
    var add = ids[1];
    var data = ids[2];
    CamlinternalOO.set_methods($$class, /* array */[
          add,
          (function (self$1, key, x) {
              self$1[data][0] = Curry._3(ContextMap[/* add */3], key, x, self$1[data][0]);
              return self$1;
            }),
          get,
          (function (self$1, key) {
              return Curry._2(ContextMap[/* find */21], key, self$1[data][0]);
            })
        ]);
    var env_init = function (env) {
      var self = CamlinternalOO.create_object_opt(0, $$class);
      self[data] = [env[1]];
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], [
              0,
              metaData
            ]);
}

var ctx1 = create(ContextMap[/* empty */0]);

var tmp = Caml_oo_curry.js3(4846113, 1, ctx1, "key", 42);

var result = Caml_oo_curry.js2(5144726, 2, tmp, "key");

var match = +(result === 42);

if (match !== 0) {
  console.log("SUCCESS");
} else {
  console.log("ERROR");
}

var ctx2 = create(ContextMap[/* empty */0]);

var tmp$1 = Caml_oo_curry.js3(4846113, 4, tmp$2, "key", 43);

var tmp$2 = Caml_oo_curry.js3(4846113, 3, ctx2, "key", 42);

var result$1 = Caml_oo_curry.js2(5144726, 5, tmp$1, "key");

var match$1 = +(result$1 === 42);

if (match$1 !== 0) {
  console.log("SUCCESS");
} else {
  console.log("ERROR");
}

exports.ContextMap = ContextMap;
exports.create     = create;
exports.ctx1       = ctx1;
exports.ctx2       = ctx2;
exports.result     = result$1;
/* ContextMap Not a pure module */
